# Generated by Django 3.1.7 on 2021-04-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(help_text='Stored each password as an encrypted text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('basicinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='frama.basicinformation')),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frama.directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frama.user')),
            ],
            bases=('frama.basicinformation',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('basicinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='frama.basicinformation')),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frama.directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frama.user')),
            ],
            bases=('frama.basicinformation',),
        ),
    ]
